### ISSUE TITLE
[팀 회의] 튜터님 피드백 후 회의 진행

### ISSUE THREAD

**Issue by haedal-uni** [Lluora/DangDang#1]
### 💡api 설계
👉🏻 ***issue***를 이용한다.

<br>

### 💡issue 등록
 issue 등록하는 틀만 잡고 각자 편하게 ***issue***등록하는건 어떨까? 

👉🏻틀은 `[]`(대괄호)로 주제가 무엇인지 적고 그 뒤는 자유롭게 적는다.
***Review in progress***를 이용해서 피드백을 받을 ***issue***들을 등록한다.
ex. [기능 추가], [오류 수정], [기능 변경], [개선 제안]

<br>

### 💡테이블 짜기
각자 맡은 역할에 테이블을 짜는데 tool을 어떤 것으로 할까?
ex) 유료 - aquerytool //  각자 그리기? or 엑셀? or 캡쳐? 
👉🏻 무료 - exerd를 이용한다.

<br>

### 💡심화 기능 추가
지도 범위, 베스트 사진 시간 정해서 내리기, 댓글 기능 수정, 내가 쓴 글 모아보기, 동영상 등록 
👉🏻기존 기능을 구현한 다음 진행할 예정이다.

**Comment by great-psycho** [comment]
Good!!!!

**Comment by manijang2** [comment]
제협님도 확인하신 듯 하여 승인 상태로 이슈를 옮기겠습니다. 이슈를 Done 으로 옮겨주시고 이슈 닫아주세요. - @Lluora
