### ISSUE TITLE
[❗필독 공지❗] Wiki, 커밋 메세지, Issue 관리

### ISSUE THREAD

**Issue by haedal-uni** [Lluora/DangDang#24]
### Wiki 페이지 각자 맡은 부분 추가해주세요
api 설계, 와이어프레임

* 페이지 추가하실 분들은 아래 ***comment*** or  ***issue***로 제안해주세요

<br>

### 커밋 메세지 틀대로 올려주세요
⭕ [add] OOO 기능 추가 [#2222]  
❌ [add] OOO 기능 추가  #2222  :  (이슈번호에 **대괄호** 안넣음)
❌ [Add] OOO 기능 추가  #2222  :  (add가 아닌 Add로 입력함)
❌ [add] OOO 기능 추가  ` ______`  : (이슈번호 **미입력**)
                     
       
add 외의 형식은 wiki를 참고해주세요
https://github.com/Lluora/DangDang/wiki/Git

<br>

#### 본인의 issue만 issue가 종료되면 Done에서 삭제해주세요.

Done에는 공지 or 꼭 봐야하는 issue만 남기겠습니다. ***(공지 이동 x)***

**Comment by manijang2** [comment]
확인했습니다!
