### ISSUE TITLE
[오류] .attr is not a function

### ISSUE THREAD

**Issue by haedal-uni** [Lluora/DangDang#28]
img src에 있는 url 주소를 가져오려고 하는데 오류가 뜹니다.

![image](https://user-images.githubusercontent.com/74857364/144220514-e71f3262-d194-497e-8339-5260d2f27b99.png)

**Comment by manijang2** [comment]
소스코드를 보니까 업로드한 이미지의 미리보기 이미지의 경로를 가지고오려고 하신거 같은데요.(실제로 코드가 소스코드에 없어서 못찾을 수 있었는데 찾았네요 ^^;;) 제생각에는 업로드한 이미지는 아직 서버에 업로드를 하기 전이기 때문에 이미지의 경로는 없는 상태 입니다.(정확하게는 메모리에만 업로드 한 상태) 그래서 코드는 맞지만 이미지의 경로는 읽지 못하는 상태인 것 같습니다.  아래 그림에서 이미지의 경로가 비정상적이란것을 확인하실 수 있어요.

![스크린샷 2021-12-02 오전 12 09 38](https://user-images.githubusercontent.com/29498316/144260596-c2ae865c-4774-4fa7-b3d5-ca8fe507f8c8.png)

서버에 업로드를 하기 전에 서버에 업로드 한 후 생성되는 이미지경로를 읽을 시도를 어떻게 하게 되셨는지 조금더 고민해보셔야 할 것 같아요!

@Lluora

**Comment by haedal-uni** [comment]
오류 해결했습니다.
