### ISSUE TITLE
[팀 회의] 개인 면담 후 회의 진행

### ISSUE THREAD

**Issue by haedal-uni** [Lluora/DangDang#3]
### 1. 회의 시간 설정
타임박스 이용한다. ⏰
회의 시간은 **12:45~13:00**
한 사람당 3분 씩, 질의응답은 2분 이내 

팀원 발표가 끝난 후 최종 마무리 1분(필요 시)
만약 질의응답에서 2분이 초과되었을 때 답변을 받지 못했다면 슬랙을 이용(형식에 맞춰 작성한다.)

<br>

### 2. ISSUE Label
Label 정리 
→ 라벨 추가 or 수정

<br>

### 3. 기술적 챌린지 CRUD
CRUD를 작업하다가 기존 기능에서 다른 기능(ex. GET → CREATE or DELETE) 으로 바꾸고 싶으면
Issue로 등록하고 Review in progress에 올린 후 팀원들에게 피드백을 받는다.
팀원들이 더 나은 방법이라 판단하여 comment를 주면 그것으로 진행한다.

**Comment by great-psycho** [comment]
Good!!

**Comment by manijang2** [comment]
확인하였습니다! :) 제협님도 확인하신 듯 하여 승인 상태로 옮기도록 하겠습니다.

**Comment by manijang2** [comment]
이슈를 Done 상태로 옮겨주시고 이슈 닫아주세요 ^^ @Lluora
