### ISSUE TITLE
[기능 제안]

### ISSUE THREAD

**Issue by haedal-uni** [Lluora/DangDang#36]
현재 제가 주소 검색을 하면 장소를 띄워와야하는데 어떤 기능을 활용해야 할지 의견을 묻고싶습니다.

1. 카카오 api를 이용한다.
👍🏻 현재 api를 이용하면 가장 나을 방법
👎🏻해당 장소가 없을 수 있다.

2. 구글 api를 이용한다. 
👍🏻구글링을 해보니 장소 자동완성 기능이 있는 것으로 뜬다.
👎🏻유료

3. 네이버 api를 이용한다.
❓사용해본 적 없어서 결과 값 어떻게 나오는지 모름

4. 일단 검색 값을 입력해서 값을 db에 저장만 해놓는다.

**Comment by haedal-uni** [comment]
현재는 4번으로 틀만 잡았습니다.

**Comment by manijang2** [comment]
구글 API 와 네이버 API 를 이용한다고 해당 장소가 없다(문제가 해결된다) 라는 가정은 하면 안되요.
장기적인 문제로 보면 장소가 없는 이유를 카카오에 문의하여 왜 카카오 API에 장소가 없는지 이유를 확인해봐야 합니다.
기술적인 문제가 있는지, 단순히 카카오에서 등록을 안하는건지, 정책이나 법에 어긋한 문제인지 기타 등등..
물론 1번과 3번, 1번과 2번을 병행해서 사용 가능은 하나 프로젝트가 며칠 안남았으니 1번에만 집중하는 것도 좋을 듯 합니다.
장소가 너무 많이 검색이 안된다. 이러면 카카오를 사용하는 것이 아니라 다른 API를 사용해봐야 할듯 해요.

@haedal-uni

**Comment by haedal-uni** [comment]
해당 장소가 없다 라는 가정을 하면 안되는 이유는 뭔가요?

이 전 프로젝트 하실 때 카카오 api 관련 문서를 보지 않으셔서 질문을 하신건지는 모르겠으나
장소 검색 결과는 최대 45개로 제공되어서 페이지당 15개를 제공한다고 합니다.

그래서 장소 검색했을 때 나오던 장소만 계속 나오는 것 같아 
이 전 프로젝트에서도 이 점이 문제점으로 자주 언급이 되었습니다.
그래서 현 프로젝트에서도 이 문제점을 어떻게 해결할지 이 전부터 말씀 드렸던 것 입니다.

그리고 2일 전에 회의에서 1번으로 하는 방안으로 정하지 않았나요..???

@manijang2

**Comment by haedal-uni** [comment]
3차 프로젝트 완료
