### ISSUE TITLE
[기능추가] HTML/CSS 메인 페이지 작업

### ISSUE THREAD

**Issue by great-psycho** [Lluora/DangDang#4]
메인페이지
<figure>
    <img src="https://user-images.githubusercontent.com/90807141/143394376-29f0beb8-7942-40cd-9859-ed396ca2fa74.png">
</figure>

**Comment by manijang2** [comment]
제목에 어떤 페이지를 수정하는지 언급이 되지 않아 마이페이지 수정작업이라고 언급해주시면 어떨까요..? ☺️ @YuJehyeop

**Comment by great-psycho** [comment]
네 작업하는 거 개별로 나눠서 이슈에 등록 하면서 하겠습니다.! ^^

**Comment by great-psycho** [comment]
#### 일단 디자인만 작업했습니다! (선만님 디자인을 최대한 따라 갔습니다.) "참고로 오늘의 강아지는?" 문구는 아직 고민에 있습니다. 

[ 추가 파일: main.html, main.css ]

<br>

<img src="https://user-images.githubusercontent.com/90807141/143483199-019fc11c-395f-4cde-a509-87ed94906b39.PNG">

**Comment by haedal-uni** [comment]
마크다운 수정 부탁드립니다.

대형견/중형견/소형견 나누는 부분은 회원가입에서 사용자가 지정하는 것으로 추가해서 분류하는 걸까요?

**Comment by great-psycho** [comment]
#### 음.. 기능 제안을 한번 해봐야 겠군요.

**Comment by manijang2** [comment]
저도 오늘의 강아지 문구는 고민이 되더라구여! 대안 있으면 댓글에 올려주세요 ㅎㅎ @YuJehyeop
