### ISSUE TITLE
[기능추가] HTML/CSS 해당 위치 사진 모아보기 페이지

### ISSUE THREAD

**Issue by great-psycho** [Lluora/DangDang#6]
![New Wireframe 1 (3)](https://user-images.githubusercontent.com/90807141/143483573-6984e537-b5f9-45c1-b7a4-d816eaa61b35.png)

**Comment by great-psycho** [comment]
grid 사용해서 작업했는데 무한 스크롤 도입할때는 flex로 구현해야할 거같습니다( 유튜브 방식 참고)
<img src="https://user-images.githubusercontent.com/90807141/143601130-c051edb2-16f2-4953-b45b-f302b4b4a414.PNG">

**Comment by haedal-uni** [comment]
확인했습니다👍🏻

**Comment by manijang2** [comment]
소스 파일명이 어떻게 되나욤..? @YuJehyeop

**Comment by great-psycho** [comment]
소스 파일명 photo 입니다.

**Comment by manijang2** [comment]
특별히 이상 없네요! 고생하셨습니다 :) @YuJehyeop  이슈 닫아주시면 되실꺼 같아요!
