### ISSUE TITLE
[기능 제안] 카카오 api 주소 검색 기능

### ISSUE THREAD

**Issue by haedal-uni** [Lluora/DangDang#7]
### 문제점
카카오 지도 api 이용시 장소 데이터 부족
(항상 나오던 것만 뜸)

<br>

### 예싱되는 문제점
사용자가 장소명을 검색했을 때 그 장소가 안뜰 수 있음

<br>

### 1차적 해결 방법
사용자가 직접 주소를 입력하게 하자

<br>

### 그에 따른 문제점
사용자가 정확한 주소를 입력할지 아닐지 장담을 할 수 없음

<br>

### 제안
사용자가 장소명을 입력하면 장소명과 주소를 크롤링하여 dropdown에 장소명을 띄워준다.
사용자가 장소를 클릭하면 해당 장소에 맞는 주소로 최종 변경되어 띄워준다.

단점 : 구현 소요 시간 계산 불가

**Comment by great-psycho** [comment]
아이디어는 좋은 거 같습니다. 구현 소여 시간이 예상 가능해질때 구현 하시면 될 거 같습니다!!

**Comment by manijang2** [comment]
튜터님이 말씀하신 기술적인 부분에 대하여 챌린지를 하고 싶다면 크롤링을 추가하면 좋을 것 같습니다.
우선 장소가 검색이 안되는 이유나 케이스를 확인하여 기능의 개선이 필요한지, 아니면 기능추가로 크롤링을 해야할지 확인이 필요합니다.

**Comment by haedal-uni** [comment]
다른 기능들을 다 구현한 다음에 다시 생각해보겠습니다.
